### ISSUE TITLE
More popup bindings

### ISSUE THREAD

**Issue by dpwiz** [haskell-game/dear-imgui.hs#132]
- `OpenPopupOnItemClick`
- `BeginPopupContextItem`
- `BeginPopupContextWindow`
- `BeginPopupContextVoid`
- `IsPopupOpen`

**Comment by Drezil** [comment]
#133  adds at least the first one. The 3 BeginXXX can already be modeld with the "withPopup"-functionality. I don't think we should expose them, because they need to be manually closed with "endPopup".

FYI: OpenPopupOnItemClick is identical to BeginPopupContextItem - the latter only has a trailing "Begin Popup" for the popup-definition afterwards instead of beforehand (i.e. with "withPopup).

**Comment by Drezil** [comment]
Whoever/whenever the rest gets bound: also fix the comment pls:
https://github.com/haskell-game/dear-imgui.hs/commit/b837d583a5a488b2691cca11cc4ac6fc4b202dc2#r67525920
